# Generated by Django 2.2.12 on 2020-06-06 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='Название категории')),
                ('description', models.TextField(blank=True, verbose_name='Описание категории')),
                ('is_active', models.BooleanField(default=True, verbose_name='Категория активна')),
            ],
            options={
                'verbose_name': 'Категория товара',
                'verbose_name_plural': 'Категории товаров',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название товара')),
                ('product_image', models.ImageField(blank=True, upload_to='products_images')),
                ('short_desc', models.CharField(blank=True, max_length=100, verbose_name='Краткое описание товара')),
                ('detailed_desc', models.TextField(blank=True, verbose_name='Подробное описание товара')),
                ('appearance', models.TextField(blank=True, verbose_name='Описание внешнего вида товара')),
                ('specifications', models.TextField(verbose_name='Характеристики товара')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Стоимость товара')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Количество товара в наличии')),
                ('is_active', models.BooleanField(default=True, verbose_name='Товар активен')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.ProductCategory')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
