# Generated by Django 2.2.12 on 2020-05-17 21:07

from django.db import migrations
from authnapp.models import ShopUser


def forwards_func(apps, schema_editor):
    product_category_model = apps.get_model("mainapp", "ProductCategory")  # Load model for make changes
    product_model = apps.get_model("mainapp", "Product")  # Load model for make changes
    # user_model = apps.get_model("authnapp", "ShopUser")  # Load model for make changes

    # Create new category
    product_category_object = product_category_model.objects.create(
        pk=1,
        title="Мужские часы",
        description="Lorem ipsum dolor sit amet",
        is_active=True,
    )
    
    # Create new products in this category
    product_model.objects.create(
        pk=1,
        category=product_category_object,  # Foreign key
        name="Longines HydroConquest L3.740.4.96.6",
        product_image="products_images/longines_hydroconquest_L3.740.4.96.6.jpg",
        short_desc="Lorem ipsum dolor sit amet, consectetur adipisicing elit. Laboriosam, ipsa",
        detailed_desc="Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolorum itaque vel qui assumenda? Dolorem, optio veritatis non expedita at explicabo soluta commodi quae asperiores, facilis obcaecati rerum, temporibus ut consectetur.",
        appearance="Lorem ipsum dolor sit amet, consectetur adipisicing elit. Inventore culpa dolorum commodi sit maiores illo quae dolore facere! Sit, possimus.",
        specifications="Материал корпуса: Сталь;Механизм: Кварц;Браслет: Браслет;Диаметр корпуса: 41 мм.;Форма корпуса: Круг;Страна производитель: Швейцария",
        price=65500,
        quantity=4,
        is_active=True,
    )

    product_model.objects.create(
        pk=2,
        category=product_category_object,  # Foreign key
        name="Longines Master Collection L2.773.4.78.5",
        product_image="products_images/longines_master_collection_L2.773.4.78.5.jpg",
        short_desc="Lorem ipsum dolor sit amet, consectetur adipisicing elit. Laboriosam, ipsa",
        detailed_desc="Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolorum itaque vel qui assumenda? Dolorem, optio veritatis non expedita at explicabo soluta commodi quae asperiores, facilis obcaecati rerum, temporibus ut consectetur.",
        appearance="Lorem ipsum dolor sit amet, consectetur adipisicing elit. Inventore culpa dolorum commodi sit maiores illo quae dolore facere! Sit, possimus.",
        specifications="Материал корпуса: Золото;Механизм: Механика;Браслет: Кожаный ремень;Диаметр корпуса: 42 мм.;Форма корпуса: Круг;Страна производитель: Швейцария",
        price=233500,
        quantity=2,
        is_active=True,
    )

    product_model.objects.create(
        pk=3,
        category=product_category_object,  # Foreign key
        name="Ulysse Nardin Marine 1186-126-3/43",
        product_image="products_images/ulysse_nardin_marine_1186-126-3.jpg",
        short_desc="Lorem ipsum dolor sit amet, consectetur adipisicing elit. Laboriosam, ipsa",
        detailed_desc="Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolorum itaque vel qui assumenda? Dolorem, optio veritatis non expedita at explicabo soluta commodi quae asperiores, facilis obcaecati rerum, temporibus ut consectetur.",
        appearance="Lorem ipsum dolor sit amet, consectetur adipisicing elit. Inventore culpa dolorum commodi sit maiores illo quae dolore facere! Sit, possimus.",
        specifications="Материал корпуса: Золото;Механизм: Механика;Браслет: Каучук;Диаметр корпуса: 43 мм.;Форма корпуса: Круг;Страна производитель: Швейцария",
        price=1033200,
        quantity=1,
        is_active=True,
    )
    del product_category_object  # Delete link for category


    # Create new category
    product_category_object = product_category_model.objects.create(
        pk=2,
        title="Женские часы",
        description="Lorem ipsum dolor sit amet",
        is_active=True,
    )

    # Create new products in this category
    product_model.objects.create(
        pk=4,
        category=product_category_object,  # Foreign key
        name="Longines La Grande Classique L4.209.4.58.6",
        product_image="products_images/longines_la_grande_classique_L4.209.4.58.6.jpg",
        short_desc="Lorem ipsum dolor sit amet, consectetur adipisicing elit. Laboriosam, ipsa",
        detailed_desc="Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolorum itaque vel qui assumenda? Dolorem, optio veritatis non expedita at explicabo soluta commodi quae asperiores, facilis obcaecati rerum, temporibus ut consectetur.",
        appearance="Lorem ipsum dolor sit amet, consectetur adipisicing elit. Inventore culpa dolorum commodi sit maiores illo quae dolore facere! Sit, possimus.",
        specifications="Материал корпуса: Сталь;Механизм: Кварц;Браслет: Браслет;Диаметр корпуса: 24 мм.;Форма корпуса: Круг;Страна производитель: Швейцария",
        price=87300,
        quantity=2,
        is_active=True,
    )
    del product_category_object  # Delete link for category

    # Create super user
    ShopUser.objects.create_superuser('django', 'django@geekshop.local', 'geekbrains', age=20)

def reverse_func(apps, schema_editor):
    product_category_model = apps.get_model("mainapp", "ProductCategory")  # Load model for make changes

    # Delete all objects
    product_category_model.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [("mainapp", "0001_initial")]

    operations = [migrations.RunPython(forwards_func, reverse_func)]
