# Generated by Django 2.2.12 on 2020-06-18 09:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authnapp', '0005_create_profiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 20, 9, 28, 57, 205697, tzinfo=utc), verbose_name='Актуальность ключа'),
        ),
    ]
